# Generated by Django 6.0.2 on 2026-02-18 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_popularity_range'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_popularity_1_5',
        ),
        migrations.AlterField(
            model_name='event',
            name='popularity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
