# Generated by Django 6.0.2 on 2026-03-27 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('role_changed', 'Role Changed'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('event_approved', 'Event Approved'), ('event_rejected', 'Event Rejected'), ('event_finished', 'Event Finished')], max_length=40),
        ),
    ]
